# MODEL SELECTION CLASSIFICATION

## Importing The Libraries & Dataset

In [1]:
# IMPORTING THE LIBRARIES

import numpy as np
import pandas as pd

from matplotlib import pyplot as plt
%matplotlib inline

import seaborn as sns

In [2]:
# IMPORTING THE DATASET

data = pd.read_csv('Data.csv')

In [3]:
# CHECKING THE HEAD OF DATA

data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [4]:
# CHECKING THE INFO OF THE DATA

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [5]:
# SEPARATING THE DEPENDENT & INDEPENDENT VARIABLES

X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [6]:
# TO AVOID EXPONENTIAL VALUES

np.set_printoptions(suppress = True)

## Dividing Data Into Train Test Split

In [7]:
# IMPORTING THE train_test_split

from sklearn.model_selection import train_test_split

# DIVIDING DATA INTO TRAINING AND TESTING DATA

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling Of Independent Variables

In [8]:
# IMPORTING THE StandardScaler CLASS FOR FEATURE SCALING

from sklearn.preprocessing import StandardScaler

# CREATING AN INSTANCE OF StandardScaler CLASS

scaler = StandardScaler()

In [9]:
# CHECKING X_train BEFORE SCALING

X_train

array([[ 142932,       7,       6, ...,       9,      10,       2],
       [1120559,       8,       3, ...,       8,       9,       8],
       [1254538,       8,      10, ...,      10,      10,       1],
       ...,
       [1214092,       1,       1, ...,       1,       1,       1],
       [1303489,       3,       1, ...,       2,       1,       1],
       [ 378275,      10,       9, ...,       7,       7,       1]],
      dtype=int64)

In [10]:
# CHECKING X_test BEFORE SCALING

X_test

array([[1173347,       1,       1, ...,       1,       1,       1],
       [1156017,       3,       1, ...,       2,       1,       1],
       [ 706426,       5,       5, ...,       4,       3,       1],
       ...,
       [ 764974,       5,       1, ...,       3,       1,       2],
       [1137156,       2,       2, ...,       7,       1,       1],
       [1160476,       2,       1, ...,       3,       1,       1]],
      dtype=int64)

In [11]:
# FEATURE SCALING OF X_train

X_train = scaler.fit_transform(X_train)

# FEATURE SCALING X_test

X_test = scaler.fit_transform(X_test)

## Creating, Training & Making Predictions From The Different Models

In [22]:
# IMPORTING THE LogisticRegression CLASS

from sklearn.linear_model import LogisticRegression

# CREATING AN INSTANCE OF LogisticRegression

classifier1 = LogisticRegression()

In [23]:
# FITTING THE MODEL

classifier1.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
# GETTING PREDICTION FORM MODEL

y_pred_1 = classifier1.predict(X_test)

In [25]:
# IMPORTING THE METRICS FOR CLASSIFICATION THE ACCURACY, CONFUSION MATRIX, & CLASSIFICATION REPORT

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [26]:
# EVALUATING THE LogisticRegression MODEL

# PRINTING THE ACCURACY SCORE, CONFUSION MATRIX, & CLASSIFICATION REPORT

print("The Accuracy Score Is: ", accuracy_score(y_pred_1, y_test))
print("\n")
print("The Confusion Matrix Is: ","\n","\n",confusion_matrix(y_pred_1, y_test))
print("\n")
print("The Classification Report is: ","\n","\n",classification_report(y_pred_1, y_test))

The Accuracy Score Is:  0.9473684210526315


The Confusion Matrix Is:  
 
 [[103   5]
 [  4  59]]


The Classification Report is:  
 
               precision    recall  f1-score   support

           2       0.96      0.95      0.96       108
           4       0.92      0.94      0.93        63

    accuracy                           0.95       171
   macro avg       0.94      0.95      0.94       171
weighted avg       0.95      0.95      0.95       171



In [38]:
# IMPORTING THE KNeighborsClassifier CLASS

from sklearn.neighbors import KNeighborsClassifier

# CREATING AN INSTANCE OF KNEighborsClassifier

classifier2 = KNeighborsClassifier()

In [40]:
# FITTING THE MODEL

classifier2.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [41]:
# GETTING PREDICTION FORM MODEL

y_pred_2 = classifier2.predict(X_test)

In [42]:
# EVALUATING THE KNeighborsClassifier MODEL

# PRINTING THE ACCURACY SCORE, CONFUSION MATRIX, & CLASSIFICATION REPORT

print("The Accuracy Score Is: ", accuracy_score(y_pred_2, y_test))
print("\n")
print("The Confusion Matrix Is: ","\n","\n",confusion_matrix(y_pred_2, y_test))
print("\n")
print("The Classification Report is: ","\n","\n",classification_report(y_pred_2, y_test))

The Accuracy Score Is:  0.9415204678362573


The Confusion Matrix Is:  
 
 [[102   5]
 [  5  59]]


The Classification Report is:  
 
               precision    recall  f1-score   support

           2       0.95      0.95      0.95       107
           4       0.92      0.92      0.92        64

    accuracy                           0.94       171
   macro avg       0.94      0.94      0.94       171
weighted avg       0.94      0.94      0.94       171



In [43]:
# IMPORTING THE GaussianNB CLASS

from sklearn.naive_bayes import GaussianNB

# CREATING AN INSTANCE OF GaussianNB

classifier3 = GaussianNB()

In [45]:
# FITTING THE MODEL

classifier3.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [46]:
# GETTING PREDICTION FORM MODEL

y_pred_3 = classifier3.predict(X_test)

In [47]:
# EVALUATING THE GaussianNB MODEL

# PRINTING THE ACCURACY SCORE, CONFUSION MATRIX, & CLASSIFICATION REPORT

print("The Accuracy Score Is: ", accuracy_score(y_pred_3, y_test))
print("\n")
print("The Confusion Matrix Is: ","\n","\n",confusion_matrix(y_pred_3, y_test))
print("\n")
print("The Classification Report is: ","\n","\n",classification_report(y_pred_3, y_test))

The Accuracy Score Is:  0.9415204678362573


The Confusion Matrix Is:  
 
 [[100   3]
 [  7  61]]


The Classification Report is:  
 
               precision    recall  f1-score   support

           2       0.93      0.97      0.95       103
           4       0.95      0.90      0.92        68

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.94       171
weighted avg       0.94      0.94      0.94       171



In [48]:
# IMPORTING THE SVC CLASS

from sklearn.svm import SVC

# CREATING AN INSTANCE OF SVC

classifier4 = SVC(kernel = 'linear')

In [50]:
# FITTING THE MODEL

classifier4.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [51]:
# GETTING PREDICTIONS FROM MODEL

y_pred_4  = classifier4.predict(X_test)

In [52]:
# EVALUATING THE Linear SVC MODEL

# PRINTING THE ACCURACY SCORE, CONFUSION MATRIX, & CLASSIFICATION REPORT

print("The Accuracy Score Is: ", accuracy_score(y_pred_4, y_test))
print("\n")
print("The Confusion Matrix Is: ","\n","\n",confusion_matrix(y_pred_4, y_test))
print("\n")
print("The Classification Report is: ","\n","\n",classification_report(y_pred_4, y_test))

The Accuracy Score Is:  0.9415204678362573


The Confusion Matrix Is:  
 
 [[102   5]
 [  5  59]]


The Classification Report is:  
 
               precision    recall  f1-score   support

           2       0.95      0.95      0.95       107
           4       0.92      0.92      0.92        64

    accuracy                           0.94       171
   macro avg       0.94      0.94      0.94       171
weighted avg       0.94      0.94      0.94       171



In [53]:
# IMPORTING THE SVC CLASS

from sklearn.svm import SVC

# CREATING AN INSTANCE OF SVC

classifier5 = SVC(kernel = 'rbf')

In [54]:
# FITTING THE MODEL

classifier5.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [55]:
# GETTING PREDICTIONS FROM MODEL

y_pred_5  = classifier5.predict(X_test)

In [56]:
# EVALUATING THE Kernel SVC MODEL

# PRINTING THE ACCURACY SCORE, CONFUSION MATRIX, & CLASSIFICATION REPORT

print("The Accuracy Score Is: ", accuracy_score(y_pred_5, y_test))
print("\n")
print("The Confusion Matrix Is: ","\n","\n",confusion_matrix(y_pred_5, y_test))
print("\n")
print("The Classification Report is: ","\n","\n",classification_report(y_pred_5, y_test))

The Accuracy Score Is:  0.9473684210526315


The Confusion Matrix Is:  
 
 [[101   3]
 [  6  61]]


The Classification Report is:  
 
               precision    recall  f1-score   support

           2       0.94      0.97      0.96       104
           4       0.95      0.91      0.93        67

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171



In [58]:
# IMPORTING THE DecisionTreeClassifier CLASS

from sklearn.tree import DecisionTreeClassifier

# CREATING AN INSTANCE OF DecisionTreeClassifier

classifier6 = DecisionTreeClassifier(criterion = 'entropy')

In [59]:
# FITTING THE MODEL

classifier6.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [60]:
# GETTING PREDICTIONS FROM MODEL

y_pred_6  = classifier6.predict(X_test)

In [61]:
# EVALUATING THE DecisionTreeClassifier MODEL

# PRINTING THE ACCURACY SCORE, CONFUSION MATRIX, & CLASSIFICATION REPORT

print("The Accuracy Score Is: ", accuracy_score(y_pred_6, y_test))
print("\n")
print("The Confusion Matrix Is: ","\n","\n",confusion_matrix(y_pred_6, y_test))
print("\n")
print("The Classification Report is: ","\n","\n",classification_report(y_pred_6, y_test))

The Accuracy Score Is:  0.9532163742690059


The Confusion Matrix Is:  
 
 [[103   4]
 [  4  60]]


The Classification Report is:  
 
               precision    recall  f1-score   support

           2       0.96      0.96      0.96       107
           4       0.94      0.94      0.94        64

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [62]:
# IMPORTING THE RandomForestClassifier CLASS

from sklearn.ensemble import RandomForestClassifier

# CREATING AN INSTANCE OF RandomForestClassifier

classifier7 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [63]:
# FITTING THE MODEL

classifier7.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [64]:
# GETTING PREDICTIONS FROM MODEL

y_pred_7  = classifier7.predict(X_test)

In [65]:
# EVALUATING THE RandomForestClassifier MODEL

# PRINTING THE ACCURACY SCORE, CONFUSION MATRIX, & CLASSIFICATION REPORT

print("The Accuracy Score Is: ", accuracy_score(y_pred_7, y_test))
print("\n")
print("The Confusion Matrix Is: ","\n","\n",confusion_matrix(y_pred_7, y_test))
print("\n")
print("The Classification Report is: ","\n","\n",classification_report(y_pred_7, y_test))

The Accuracy Score Is:  0.9590643274853801


The Confusion Matrix Is:  
 
 [[103   3]
 [  4  61]]


The Classification Report is:  
 
               precision    recall  f1-score   support

           2       0.96      0.97      0.97       106
           4       0.95      0.94      0.95        65

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171

